// employees
export const GET_LIST_EMPLOYEES_REQUEST = 'GET_LIST_EMPLOYEES_REQUEST';
export const GET_LIST_EMPLOYEES_SUCCESS = 'GET_LIST_EMPLOYEES_SUCCESS';
export const GET_LIST_EMPLOYEES_FAILURE = 'GET_LIST_EMPLOYEES_FAILURE';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_FAILURE = 'DELETE_EMPLOYEE_FAILURE';
export const ADD_EMPLOYEE_REQUEST = 'ADD_EMPLOYEE_REQUEST';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAILURE = 'ADD_EMPLOYEE_FAILURE';
export const EDIT_EMPLOYEE_REQUEST = 'EDIT_EMPlOYEE_REQUEST';
export const EDIT_EMPLOYEE_SUCCESS = 'EDIT_EMPLOYEE_SUCCESS';
export const EDIT_EMPLOYEE_FAILURE = 'EDIT_EMPLOYEE_FAILURE';

//Leaves
export const GET_LIST_LEAVES_REQUEST = 'GET_LIST_EMPLOYEES_REQUEST';
export const GET_LIST_LEAVES_SUCCESS = 'GET_LIST_EMPLOYEES_SUCCESS';
export const GET_LIST_LEAVES_FAILURE = 'GET_LIST_EMPLOYEES_FAILURE';
export const DELETE_LEAVE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_LEAVE_FAILURE = 'DELETE_EMPLOYEE_FAILURE';
export const ADD_LEAVE_REQUEST = 'ADD_EMPLOYEE_REQUEST';
export const ADD_LEAVE_SUCCESS = 'ADD_LEAVE_SUCCESS';
export const ADD_LEAVE_FAILURE = 'ADD_LEAVE_FAILURE';
export const EDIT_LEAVE_REQUEST = 'EDIT_LEAVE_REQUEST';
export const EDIT_LEAVE_SUCCESS = 'EDIT_LEAVE_SUCCESS';
export const EDIT_LEAVE_FAILURE = 'EDIT_LEAVE_FAILURE';